"""
Example Usage: Converting Models from your NN Generator Project

This script shows how to use the Catapult conversion tools with
models generated by your Agentic NN Generator.
"""

import os
import sys
from pathlib import Path

# Add the conversion tools to path
SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))

from create_catapult_project import create_pytorch_catapult_project


def convert_pretrained_model():
    """
    Convert a pretrained model from the outputs directory.
    """
    
    # Find a recent pretrained output
    project_root = SCRIPT_DIR.parent
    outputs_dir = project_root / "outputs" / "pretrained"
    
    # Look for .pt files
    pt_files = list(outputs_dir.rglob("*.pt"))
    
    if not pt_files:
        print("No .pt files found in outputs/pretrained/")
        print("Train a model first using the NN Generator")
        return
    
    print(f"Found {len(pt_files)} model files:")
    for i, pt_file in enumerate(pt_files):
        print(f"  {i+1}. {pt_file}")
    
    # Use the first one as example
    model_path = pt_files[0]
    
    print(f"\nConverting: {model_path}")
    
    # Determine input shape from model name/path
    # Default to MNIST-like shape
    input_shape = (1, 1, 28, 28)
    
    # Create Catapult project
    output_dir = SCRIPT_DIR / "projects" / model_path.stem
    
    create_pytorch_catapult_project(
        model_path=str(model_path),
        output_dir=str(output_dir),
        input_shape=input_shape,
        precision="ac_fixed<16,6>",
        reuse_factor=1,
        io_type="io_stream",
        strategy="Latency"
    )
    
    print(f"\nProject created: {output_dir}")
    print("\nNext steps:")
    print(f"  scp -r {output_dir} ubuntu@10.10.8.216:~/catapult_projects/")


def convert_custom_cnn():
    """
    Convert a custom CNN model with specified architecture.
    """
    
    # Example: Convert a model you've trained
    # Adjust these paths to match your actual model
    
    project_root = Path(__file__).parent.parent
    
    # Check for Defense.pt in weights
    defense_model = project_root / "weights" / "Defense.pt"
    
    if defense_model.exists():
        print(f"Found Defense model: {defense_model}")
        
        # Create project with custom settings
        output_dir = SCRIPT_DIR / "projects" / "defense_cnn"
        
        create_pytorch_catapult_project(
            model_path=str(defense_model),
            output_dir=str(output_dir),
            model_name="defense_cnn",
            input_shape=(1, 3, 224, 224),  # Adjust based on your model
            precision="ac_fixed<16,8>",     # More integer bits for larger values
            reuse_factor=4,                  # Balance speed/area
            io_type="io_stream",
            strategy="Latency"
        )
        
        print(f"\nProject created: {output_dir}")
    else:
        print(f"Model not found: {defense_model}")
        print("Adjust the path to point to your trained model")


def convert_with_quantization_options():
    """
    Example showing different quantization/precision options.
    """
    
    print("Quantization Examples for Catapult AI NN")
    print("=" * 60)
    
    examples = [
        {
            "name": "High Accuracy",
            "precision": "ac_fixed<16,6>",
            "description": "16-bit fixed point, 6 integer bits, 10 fractional",
            "use_case": "When accuracy is critical"
        },
        {
            "name": "Low Power",
            "precision": "ac_fixed<8,4>",
            "description": "8-bit fixed point, 4 integer bits, 4 fractional",
            "use_case": "Edge devices, low power applications"
        },
        {
            "name": "Ultra Low Latency",
            "precision": "ac_fixed<4,2>",
            "description": "4-bit fixed point (experimental)",
            "use_case": "Extreme speed requirements, trained with QAT"
        },
        {
            "name": "High Dynamic Range",
            "precision": "ac_fixed<32,16>",
            "description": "32-bit fixed point",
            "use_case": "Models with large weight ranges"
        }
    ]
    
    for ex in examples:
        print(f"\n{ex['name']}:")
        print(f"  Precision: {ex['precision']}")
        print(f"  Description: {ex['description']}")
        print(f"  Use case: {ex['use_case']}")
    
    print("\n" + "=" * 60)
    print("To use: python create_catapult_project.py model.pt -p \"ac_fixed<16,6>\"")


def main():
    print("Catapult AI NN Conversion Examples")
    print("=" * 60)
    
    print("\n1. Converting a pretrained model from outputs/")
    print("-" * 40)
    try:
        convert_pretrained_model()
    except Exception as e:
        print(f"   Error: {e}")
    
    print("\n2. Converting a custom CNN model")
    print("-" * 40)
    try:
        convert_custom_cnn()
    except Exception as e:
        print(f"   Error: {e}")
    
    print("\n3. Quantization options reference")
    print("-" * 40)
    convert_with_quantization_options()


if __name__ == "__main__":
    main()
